E-Ticaret Sitesi/Sosyal-Sorumluluk-Projesi/Controllers/UyeController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Sosyal_Sorumluluk_Projesi.Models;
using System.Web.Helpers;
using System.IO;
using System.Web.Security;
using PagedList;
using PagedList.Mvc;
using System.Drawing;

namespace Sosyal_Sorumluluk_Projesi.Controllers
{
    public class UyeController : Controller
    {
        private Model1 db = new Model1();

        // GET: Uye
        public ActionResult Index(int id)
        {
            var uye = db.kullanicilars.Where(k => k.kullaniciID == id).SingleOrDefault();
           
            if (Convert.ToInt32(Session["kullaniciID"]) != uye.kullaniciID)
            {
                return HttpNotFound();
            }


            return View(uye);
         
        }

        // GET: Uye/Details/5 
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            kullanicilar kullanicilar = db.kullanicilars.Find(id);
            if (kullanicilar == null)
            {
                return HttpNotFound();
            }
            return View(kullanicilar);
        }

        public ActionResult Login()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Login(kullanicilar uye,string sifre)
        {
            var md5pass = Crypto.Hash(sifre, "MD5");
            var login = db.kullanicilars.Where(k => k.mail == uye.mail).SingleOrDefault();

            try
            { 

                if (login.mail == uye.mail && login.sifre==md5pass || login.mail == uye.mail && login.sifre==uye.sifre)
                {   
                        
                    Session["kullaniciID"] = login.kullaniciID;
                    Session["mail"] = login.mail;
                    Session["yetkiID"] = login.yetkiID;
                    Session["sifre"] = login.sifre;

                    return RedirectToAction("Index", "Home");




                }

                else if (login.mail != uye.mail)
                {
                    Session["kullaniciID"] = login.kullaniciID;
                    Session["mail"] = login.mail;
                    Session["sifre"] = login.sifre;
                    Session["yetkiID"] = login.yetkiID;



                    ViewBag.Uyari = "Kullanıcı Login Bilgilerinizi Kontrol Ediniz";
                }


                else
                {
                    ViewBag.Uyari = "Kullanıcı Login Bilgilerinizi Kontrol Ediniz";
                }




            }
            catch (NullReferenceException)
            {

               

                ViewBag.Uyari = "Kullanıcı Login Bilgilerinizi Kontrol Ediniz";

                //return RedirectToAction("Login", "Uye");

            }
           

            return View(login);



        }
        public ActionResult Logout()
        {
            Session["kullaniciID"] = null;
            Session.Abandon();
            return RedirectToAction("Index", "Home");
        }
         
           public ActionResult SifremiUnuttum()
        {
            return View();
        }
        [HttpPost]
        public ActionResult SifremiUnuttum(kullanicilar uye1)
        {
            Random rnd = new Random();
             
            var sifrem = db.kullanicilars.Where(k => k.kullaniciAdi == uye1.kullaniciAdi).SingleOrDefault();


            

            string yeniSifrem = rnd.Next(100,1000000000).ToString();
            

          
          

           

            

           



            try
            {
                
                if (sifrem.kullaniciAdi==uye1.kullaniciAdi && uye1.gizliSoruCevap=="ankara")
                { 
                     
                    uye1.sifre = yeniSifrem;
                    sifrem.sifre = uye1.sifre;
                    db.SaveChanges();
                    ViewBag.Mesaj = "Geçici Şifreniz Budur lütfen bu şifreyi değiştiriniz:" + yeniSifrem; 
                     
                }  
                else 
                {
                    ViewBag.Mesaj = "Bilgilerinizi Kontrol Ediniz";

                   
                }
                 
            }
            catch (NullReferenceException)
            {
                ViewBag.Mesaj = "Bilgilerinizi Kontrol Ediniz";

            }
             
            return View();  



        } 




        // GET: Uye/Create
        public ActionResult Create()
        {
            ViewBag.memleketID = new SelectList(db.memlekets, "memleketID", "memleketAdi");


            
            return View();
        }

        // POST: Uye/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "kullaniciID,yetkiID,memleketID,adsoyad,kullaniciAdi,mail,sifre,telefon,resim,gizliSoru,gizliSoruCevap")] kullanicilar kullanicilar,string sifre,HttpPostedFileBase resim)
        {
            var md5pass = sifre; 
                if (ModelState.IsValid)
                {
                 

                    if (resim != null)  
                    {

                        WebImage img = new WebImage(resim.InputStream);
                        FileInfo fotoinfo = new FileInfo(resim.FileName);

                        string newfoto = Guid.NewGuid().ToString() + fotoinfo.Extension;
                        img.Resize(100, 100); 
                        img.Save("~/Uploads/resimler/" + newfoto);
                        kullanicilar.resim = "/Uploads/resimler/" + newfoto;
                        kullanicilar.yetkiID = 2;
                        kullanicilar.sifre = Crypto.Hash(md5pass, "MD5");

                    //Session["kullaniciID"] = kullanicilar.kullaniciID;
                    //Session["yetkiID"] = kullanicilar.yetkiID;


                        db.kullanicilars.Add(kullanicilar);
                        db.SaveChanges();
                    Session["kullaniciID"] = kullanicilar.kullaniciID;
                    Session["mail"] = kullanicilar.mail;
                         return RedirectToAction("Index", "Home");
                   
                  
                    }

                    else
                    {
                        ModelState.AddModelError("Foto", "Foto Seçiniz:");
                    }
                     
                } 
          
            ViewBag.memleketID = new SelectList(db.memlekets, "memleketID", "memleketAdi", kullanicilar.memleketID);
           
           
            return View(kullanicilar);
        }

        // GET: Uye/Edit/5
        public ActionResult Edit(int id)
        {
            var uye = db.kullanicilars.Where(k => k.kullaniciID == id).SingleOrDefault();

            if (Convert.ToInt32(Session["kullaniciID"])!=uye.kullaniciID)
            {
                return HttpNotFound();
            }


            return View(uye);

        } 

        // POST: Uye/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "kullaniciID,yetkiID,memleketID,adsoyad,kullaniciAdi,mail,sifre,telefon,resim")] kullanicilar kullanicilar,string sifre, HttpPostedFileBase resim, int id)
        {
            var md5pass = sifre;
            if (ModelState.IsValid)
            {
                var uye1 = db.kullanicilars.Where(k => k.kullaniciID == id).SingleOrDefault();

                if (resim!=null)
                {

                    if (System.IO.File.Exists(Server.MapPath(kullanicilar.resim)))
                    {
                        System.IO.File.Delete(Server.MapPath(uye1.resim));
                    }

                    WebImage img = new WebImage(resim.InputStream);

                    FileInfo resiminfo = new FileInfo(resim.FileName);

                    string newfoto = Guid.NewGuid().ToString() + resiminfo.Extension;
                    img.Resize(150, 150);
                    img.Save("~/Uploads/uyeler/" + newfoto);
                    uye1.resim = "/Uploads/uyeler/" + newfoto;
                     
                    }

                    uye1.adsoyad = kullanicilar.adsoyad;
                    uye1.kullaniciAdi = kullanicilar.kullaniciAdi;
                    uye1.mail = kullanicilar.mail;
                uye1.sifre = Crypto.Hash(md5pass, "MD5");
                  
                    uye1.telefon = kullanicilar.telefon;
                    db.SaveChanges();
                    Session["kullaniciadi"] = kullanicilar.kullaniciID;
              
                    return RedirectToAction("Index", "Home", new { id = uye1.kullaniciID });

                    


                




                db.Entry(kullanicilar).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.memleketID = new SelectList(db.memlekets, "memleketID", "memleketAdi", kullanicilar.memleketID);
          
            return View(kullanicilar);
        }

        // GET: AdminUye/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            kullanicilar kullanicilar = db.kullanicilars.Find(id);
            if (kullanicilar == null)
            {
                return HttpNotFound();
            }
            return View(kullanicilar);
        }

        // POST: AdminUye/Delete/5
        [HttpPost, ActionName("Delete")]

E-Ticaret Sitesi/Sosyal-Sorumluluk-Projesi/Views/Uye/Create.cshtml
@model Sosyal_Sorumluluk_Projesi.Models.kullanicilar

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_LayoutPage1.cshtml";
}

<h2>Üye Kayıt Ol</h2>

@using (Html.BeginForm("Create", "Uye", FormMethod.Post, new { enctype = "multipart/form-data" })) 
{ 
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>kullanicilar</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
      
        <div class="form-group">
            @Html.LabelFor(model => model.memleketID, "memleketID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("memleketID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.memleketID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.adsoyad, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.adsoyad, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.adsoyad, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.kullaniciAdi, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.kullaniciAdi, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.kullaniciAdi, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.mail, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.mail, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.mail, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.sifre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.sifre, new { htmlAttributes = new { @class = "form-control" ,@type="password"} })
                @Html.ValidationMessageFor(model => model.sifre, "", new { @class = "text-danger" })
            </div> 
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.telefon, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.telefon, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.telefon, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.resim, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="resim" id="resim" value="" accept=".jpg,.png,.gif,.JPEG,.jpeg" class="form-control" />
                @Html.ValidationMessageFor(model => model.resim, "", new { @class = "text-danger" })
            </div>
        </div>
         
        <div class="form-group">
            @Html.LabelFor(model => model.gizliSoru, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.gizliSoru, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.gizliSoru, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.gizliSoruCevap, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.gizliSoruCevap, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.gizliSoruCevap, "", new { @class = "text-danger" })
            </div>
        </div>





        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Kaydet" class="btn btn-default" />
            </div>
        </div>
    </div>
}
 
  

E-Ticaret Sitesi/Sosyal-Sorumluluk-Projesi/Views/Uye/Delete.cshtml
@model Sosyal_Sorumluluk_Projesi.Models.kullanicilar

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_LayoutPage1.cshtml";
}

<h2>Kullanıcı Sil</h2>

<h3>Üyeliğinizi Silmek istediğinize eminmisiniz?</h3>
<div>
    <h4>kullanicilar</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.memleket.memleketAdi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.memleket.memleketAdi)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.yetki.yetkiAdi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.yetki.yetkiAdi)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.adsoyad)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.adsoyad)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.kullaniciAdi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.kullaniciAdi)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.mail)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.mail)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.sifre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.sifre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.telefon)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.telefon)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.resim)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.resim)
        </dd>

    </dl>

    @using (Html.BeginForm("Delete", "Uye", FormMethod.Post, new { enctype = "multipart/form-data" })) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color"> 
            <input type="submit" value="Sil" class="btn btn-default" /> | 
            @Html.ActionLink("Geri Dön" ,"Index/" + Session["kullaniciID"].ToString())
        </div>   
    }    
</div> 
 

E-Ticaret Sitesi/Sosyal-Sorumluluk-Projesi/Views/Uye/Edit.cshtml
@model Sosyal_Sorumluluk_Projesi.Models.kullanicilar

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_LayoutPage1.cshtml";
}

<h2>Üye Düzenle</h2>

@using (Html.BeginForm("Edit", "Uye", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>kullanicilar</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.kullaniciID)

        
    

        <div class="form-group">
            @Html.LabelFor(model => model.adsoyad, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.adsoyad, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.adsoyad, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.kullaniciAdi, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.kullaniciAdi, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.kullaniciAdi, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.mail, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.mail, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.mail, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.sifre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.sifre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.sifre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.telefon, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.telefon, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.telefon, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.resim, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="resim" id="resim" value="" accept=".jpg,.png,.gif,.JPEG,.jpeg" class="form-control" />
                @Html.ValidationMessageFor(model => model.resim, "", new { @class = "text-danger" })
            </div>
        </div> 



        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Kaydet" class="btn btn-default" />
            </div>
        </div>
    </div>
} 
 
<div>
    @Html.ActionLink("Geri Dön", "Index/" + Session["kullaniciID"].ToString())
</div>

E-Ticaret Sitesi/Sosyal-Sorumluluk-Projesi/Views/Uye/Login.cshtml
@model Sosyal_Sorumluluk_Projesi.Models.kullanicilar

@{
    ViewBag.Title = "Login";
    Layout = "~/Views/Shared/_LayoutUye.cshtml";
}

<h2>Üye Girişi</h2>

@using (Html.BeginForm("Login", "Uye", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()


    <div class="form-horizontal">
        
        
        <h4>kullanicilar</h4> 


        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
      
       

        <div class="form-group">
            @Html.LabelFor(model => model.mail, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.mail, new { htmlAttributes = new { @class = "form-control",@type="Email" , @required=""} })
                @Html.ValidationMessageFor(model => model.mail, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.sifre, htmlAttributes: new { @class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.EditorFor(model => model.sifre, new { htmlAttributes = new { @class = "form-control", @type = "password" ,@required="" } })
                @Html.ValidationMessageFor(model => model.sifre, "", new { @class = "text-danger" })
            </div>
        </div>

    
         <a href="/Uye/SifremiUnuttum" class="col-md-8">Şifremi Unuttum</a>
      


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Giriş Yap" class="btn btn-default" />
            </div>
        </div>  

        

        <span class="alert-danger h2">  @ViewBag.Uyari </span>

    </div>
}

E-Ticaret Sitesi/Sosyal-Sorumluluk-Projesi/Views/Uye/SifremiUnuttum.cshtml
@model Sosyal_Sorumluluk_Projesi.Models.kullanicilar

@{
    ViewBag.Title = "SifremiUnuttum";
    Layout = "~/Views/Shared/_LayoutUye.cshtml";
}

<h2>SifremiUnuttum</h2>

@using (Html.BeginForm("SifremiUnuttum", "Uye", FormMethod.Post, new { enctype = "multipart/form-data" })) 
{
    @Html.AntiForgeryToken() 
    
    <div class="form-horizontal">
        <h4>kullanicilar</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.kullaniciAdi, "Üyeliğinize ait kullanıcı adınızı giriniz:", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.kullaniciAdi, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.kullaniciAdi, "", new { @class = "text-danger" })
            </div>
        </div> 



      



        <div class="form-group">
            @Html.LabelFor(model => model.gizliSoruCevap, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input autocomplete="off" class="form-control" id="gizliSoruCevap" placeholder="Türkiyenin Başkenti Neresidir?" type="text" name="gizliSoruCevap" />
                @Html.ValidationMessageFor(model => model.gizliSoruCevap, "", new { @class = "text-danger" })
            </div>
        </div>
         


      

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Kaydet" class="btn btn-default" />
            </div>
        </div>
    </div> 
} 
     
   
        <p style="color:red">@ViewBag.Mesaj</p> 
       


@Html.ActionLink("Geri Dön", "Login") 

E-Ticaret Sitesi/Sosyal-Sorumluluk-Projesi/Views/Uye/UrunCreate.cshtml
@model Sosyal_Sorumluluk_Projesi.Models.urunler

@{
    ViewBag.Title = "UrunCreate";
    Layout = "~/Views/Shared/_LayoutPage1.cshtml";
}

<h2>Ürün Ekleme</h2>

@using (Html.BeginForm("UrunCreate", "Uye", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken() 
    
    <div class="form-horizontal">
        <h4>urunler</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.kategoriID, "kategori Seçiniz:", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("kategoriID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.kategoriID, "", new { @class = "text-danger" })
            </div>
        </div> 

        <div class="form-group">
            @Html.LabelFor(model => model.urunAdi, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.urunAdi, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.urunAdi, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.urunİcerik, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.urunİcerik, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.urunİcerik, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.memleketID, "Ürünün Bulunduğu İli Seçiniz:", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("memleketID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.memleketID, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.tarih, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.tarih, new { htmlAttributes = new { @class = "form-control", @type = "date" } })
                @Html.ValidationMessageFor(model => model.tarih, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.resim, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="resim" id="resim" value="" accept=".jpg,.png,.gif,.JPEG,.jpeg" class="form-control" />
                       @Html.ValidationMessageFor(model => model.resim, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.kullaniciID, "Ad ve Soyadınızı Seçiniz:", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("kullaniciID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.kullanicilar.kullaniciID, "", new { @class = "text-danger" })
            </div> 
        </div> 



      

         





        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Kaydet" class="btn btn-default" />
            </div>
        </div>
    </div>







}

<div>
    @Html.ActionLink("Geri Dön", "Urunlerim/" + Session["kullaniciID"].ToString()) 
</div>