E-Ticaret Sitesi/Sosyal-Sorumluluk-Projesi/Controllers/AdminUrunController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Sosyal_Sorumluluk_Projesi.Models;
using System.Web.Helpers;
using System.IO;
using System.Net;
using PagedList;
using PagedList.Mvc;

namespace Sosyal_Sorumluluk_Projesi.Controllers
{
    public class AdminUrunController : Controller
    {
        Model1 db = new Model1();


        // GET: AdminUrun
        public ActionResult Index(string sortOrder, string currentFilter, string searchString, int? page)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";





            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;

            var urun = from s in db.urunlers
                       select s;
            if (!String.IsNullOrEmpty(searchString))
            {
                urun = urun.Where(s => s.kategoriler.kategoriAdi.Contains(searchString)
                                       || s.memleket.memleketAdi.Contains(searchString));

            }
            switch (sortOrder)
            {
                case "name_desc":
                    urun = urun.OrderByDescending(s => s.kategoriler.kategoriAdi);
                    break;



                default:
                    urun = urun.OrderBy(s => s.kategoriler.kategoriAdi);
                    break;
            } 

            int pageSize = 3;
            int pageNumber = (page ?? 1);
            return View(urun.ToPagedList(pageNumber, pageSize));
        }

        // GET: AdminUrun/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            urunler urun = db.urunlers.Find(id);
            if (urun == null)
            {
                return HttpNotFound();
            }
            return View(urun);
        }

        // GET: AdminUrun/Create
        public ActionResult Create()
        {

            ViewBag.kategoriID = new SelectList(db.kategorilers, "kategoriID", "kategoriAdi");
            ViewBag.kullaniciID = new SelectList(db.kullanicilars, "kullaniciID", "adsoyad");
            ViewBag.memleketID = new SelectList(db.memlekets, "memleketID", "memleketAdi");

            return View();  
        }

        // POST: AdminUrun/Create
        [HttpPost]
        public ActionResult Create(urunler urun, HttpPostedFileBase resim)
        {
            ViewBag.kategoriID = new SelectList(db.kategorilers, "kategoriID", "kategoriAdi");
            ViewBag.kullaniciID = new SelectList(db.kullanicilars, "kullaniciID", "adsoyad");
            ViewBag.memleketID = new SelectList(db.memlekets, "memleketID", "memleketAdi"); 
            if (ModelState.IsValid)
            {

                if (resim != null)
                {
                    WebImage img = new WebImage(resim.InputStream);

                    FileInfo resiminfo = new FileInfo(resim.FileName);

                    string newfoto = Guid.NewGuid().ToString() + resiminfo.Extension;
                    img.Resize(800, 350);
                    img.Save("~/Uploads/urunler/" + newfoto);
                    urun.resim = "/Uploads/urunler/" + newfoto;

                   
                    


                }


                db.urunlers.Add(urun);
                db.SaveChanges();

                return RedirectToAction("Index");  



            }
            return View(urun);

        }

        // GET: AdminUrun/Edit/5
        public ActionResult Edit(int id)
        {

            var urun = db.urunlers.Where(u => u.urunID == id).SingleOrDefault();

            if (urun == null)
            {

                return HttpNotFound();
            }

            ViewBag.kategoriID = new SelectList(db.kategorilers, "kategoriID", "kategoriAdi", urun.kategoriID);



            return View(urun);
        }

        // POST: AdminUrun/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, urunler urun, HttpPostedFileBase resim)
        {

            ViewBag.kategoriID = new SelectList(db.kategorilers, "kategoriID", "kategoriAdi", urun.kategoriID);

            var urun1 = db.urunlers.Where(u => u.urunID == id).SingleOrDefault();

            if (resim != null)
            {
                if (System.IO.File.Exists(Server.MapPath(urun1.resim)))
                {
                    System.IO.File.Delete(Server.MapPath(urun1.resim));
                }

                WebImage img = new WebImage(resim.InputStream);

                FileInfo resiminfo = new FileInfo(resim.FileName);

                string newfoto = Guid.NewGuid().ToString() + resiminfo.Extension;
                img.Resize(800, 350);
                img.Save("~/Uploads/urunler/" + newfoto);
                urun1.resim = "/Uploads/urunler/" + newfoto;
                urun1.urunAdi = urun.urunAdi;
                urun1.urunİcerik = urun.urunİcerik;
                urun1.kategoriID = urun.kategoriID;
                urun1.tarih = urun.tarih; 
                db.SaveChanges();
                return RedirectToAction("Index");

              

            } 

          
           

              return View(urun);

        }

                 


  
        // GET: AdminUrun/Delete/5
        public ActionResult Delete(int id)
        {
            var urun1 = db.urunlers.Where(u => u.urunID == id).SingleOrDefault(); 
            ViewData["urunID"] = "";
            ViewData["kategoriID"] = "";
            ViewData["urunAdi"] = "";
            ViewData["urunIcerik"] = "";
            ViewData["memleketID"] = "";
            ViewData["tarih"] = "";
            ViewData["resim"] = "";
            ViewData["kullaniciID"] = "";
            ViewData["yorumID"] = "";



          

            if (urun1==null)
            {
                return HttpNotFound();
            }




            return View(urun1);
        }

        // POST: AdminUrun/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            var urun1 = db.urunlers.Where(u => u.urunID == id).SingleOrDefault();

            ViewData["urunID"] = "";
            ViewData["kategoriID"] = "";
            ViewData["urunAdi"] = "";
            ViewData["urunIcerik"] = "";
            ViewData["memleketID"] = "";
            ViewData["tarih"] = "";
            ViewData["resim"] = "";
            ViewData["kullaniciID"] = "";
            ViewData["yorumID"] = "";



            return RedirectToAction("/ArsivSil/urunID/");


            
        } 




    

         









}
}

E-Ticaret Sitesi/Sosyal-Sorumluluk-Projesi/Views/AdminUrun/ArsivSil.cshtml
@model IEnumerable<Sosyal_Sorumluluk_Projesi.Models.Arsiv>

@{
    ViewBag.Title = "ArsivSil";
    Layout = "~/Views/Shared/_LayoutPageAdmin.cshtml";
}

<h2>ArsivSil</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.urunID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.kategoriID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.urunAdi)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.urunİcerik)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.memleketID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.tarih)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.resim)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.kullaniciID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.yorumID)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>  
            @TempData["urunID"] 
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.kategoriID)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.urunAdi)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.urunİcerik)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.memleketID)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.tarih)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.resim)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.kullaniciID)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.yorumID)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.ArsivID }) |
            @Html.ActionLink("Details", "Details", new { id=item.ArsivID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ArsivID })
        </td>
    </tr>
}

</table>

E-Ticaret Sitesi/Sosyal-Sorumluluk-Projesi/Views/AdminUrun/Create.cshtml
@model Sosyal_Sorumluluk_Projesi.Models.urunler

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_LayoutPageAdmin.cshtml";
}

<h2>Ürün Ekle</h2>

@using (Html.BeginForm("Create","AdminUrun",FormMethod.Post,new { enctype="multipart/form-data"}))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>urunler</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.kategoriID, "kategori Seçiniz:", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("kategoriID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.kategoriID, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.kullaniciID, "Ad ve Soyadınızı Seçiniz:", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("kullaniciID", null, htmlAttributes: new { @class = "form-control" }) 
                @Html.ValidationMessageFor(model => model.kullaniciID, "", new { @class = "text-danger" })
            </div>
        </div>








        <div class="form-group">
            @Html.LabelFor(model => model.urunAdi, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.urunAdi, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.urunAdi, "", new { @class = "text-danger" })
            </div>
        </div>

       
        <div class="form-group">
            @Html.LabelFor(model => model.urunİcerik, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.urunİcerik, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.urunİcerik, "", new { @class = "text-danger" })
            </div>
        </div> 


        <div class="form-group">
            @Html.LabelFor(model => model.resim, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="resim" id="resim" value="" accept=".jpg,.png,.gif,.JPEG,.jpeg" class="form-control" />
                @Html.ValidationMessageFor(model => model.resim, "", new { @class = "text-danger" })
            </div>
        </div>
  






        <div class="form-group">
            @Html.LabelFor(model => model.tarih, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.tarih, new { htmlAttributes = new { @class = "form-control" ,@type="date"} })
                @Html.ValidationMessageFor(model => model.tarih, "", new { @class = "text-danger" })
            </div>
        </div>


        

        <div class="form-group">
            @Html.LabelFor(model => model.memleketID, "Ürünün Bulunduğu İli Seçiniz:", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("memleketID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.memleketID, "", new { @class = "text-danger" })
            </div>
        </div>

         
         
     






        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Kaydet" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Geri Dön", "Index")
</div>

E-Ticaret Sitesi/Sosyal-Sorumluluk-Projesi/Views/AdminUrun/Delete.cshtml
@model Sosyal_Sorumluluk_Projesi.Models.urunler

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_LayoutPageAdmin.cshtml";
}

<h2>Ürün Silme</h2>

<h3>Bu ürünü silmek istiyormusunuz ?</h3>
<div>
    <h4>urunler</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.kategoriler.kategoriAdi)
        </dt> 

        <dd>
            @Html.DisplayFor(model => model.kategoriler.kategoriAdi)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.kullanicilar.adsoyad)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.kullanicilar.adsoyad)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.memleket.memleketAdi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.memleket.memleketAdi)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.urunAdi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.urunAdi)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.resim)
        </dt>

        <dd>
            <img  width="75" src="@Model.resim" alt="Alternate Text" />
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.urunİcerik)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.urunİcerik)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.tarih)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tarih)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Sil" class="btn btn-default" /> |
            @Html.ActionLink("Geri Dön", "Index")
        </div>
    }
</div>

E-Ticaret Sitesi/Sosyal-Sorumluluk-Projesi/Views/AdminUrun/Edit.cshtml
@model Sosyal_Sorumluluk_Projesi.Models.urunler



@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_LayoutPageAdmin.cshtml";
}

<h2>Ürün Düzenleme</h2>

@using (Html.BeginForm("Edit", "AdminUrun", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>urunler</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.urunID) 

        <div class="form-group">
            @Html.HiddenFor(model => model.kategoriID, new { @class = "control-label col-md-2" }) 
            <div class="col-md-10">
                @*@Html.DropDownList("kategoriID", null, htmlAttributes: new { @class = "form-control" })*@
                @Html.ValidationMessageFor(model => model.kategoriID, "", new { @class = "text-danger" })
            </div>
        </div>  



        <div class="form-group">
            @Html.HiddenFor(model => model.kullaniciID, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*@Html.DropDownList("kullaniciID", null, htmlAttributes: new { @class = "form-control" })*@
                @Html.ValidationMessageFor(model => model.kullaniciID, "", new { @class = "text-danger" })
            </div>
        </div>







        <div class="form-group">
            @Html.LabelFor(model => model.urunAdi, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.urunAdi, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.urunAdi, "", new { @class = "text-danger" })
            </div>
        </div>
         

        <div class="form-group">
            @Html.LabelFor(model => model.urunİcerik, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.urunİcerik, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.urunİcerik, "", new { @class = "text-danger" })
            </div>
        </div>






        <div class="form-group">
            @Html.Label("Eski Foto", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <img width="75" src="@Model.resim" alt="" />
                @Html.ValidationMessageFor(model => model.resim, "", new { @class = "text-danger" })
            </div>
        </div>






        <div class="form-group">
            @Html.LabelFor(model => model.resim, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="resim" id="resim" value="" accept=".jpg,.png,.gif,.JPEG,.jpeg" class="form-control" />
                @Html.ValidationMessageFor(model => model.resim, "", new { @class = "text-danger" })
            </div>
        </div>

     
        <div class="form-group">
            @Html.LabelFor(model => model.tarih, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.tarih, new { htmlAttributes = new { @class = "form-control", @type = "date" } })
                @Html.ValidationMessageFor(model => model.tarih, "", new { @class = "text-danger" })
            </div>
        </div>


     
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Kaydet" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Geri Dön", "Index")
</div>

E-Ticaret Sitesi/Sosyal-Sorumluluk-Projesi/Views/AdminUrun/Index.cshtml
@model IPagedList<Sosyal_Sorumluluk_Projesi.Models.urunler>


@using PagedList
@using PagedList.Mvc



@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutPageAdmin.cshtml";
}

<h2>Ürünler</h2>

<p>
    @Html.ActionLink("Ürün Ekle", "Create")
</p> 



@using (Html.BeginForm("Index", "AdminUrun", FormMethod.Get))
{
    <p>
        İsme Göre Bul: @Html.TextBox("SearchString", ViewBag.CurrentFilter as string)
        <input type="submit" value="Ara" />
    </p>
}









<table class="table">
    <tr>
        <th>
            @Html.ActionLink("Kategori Adı", "Index", new { sortOrder = ViewBag.NameSortParm, currentFilter = ViewBag.CurrentFilter })
        </th>
        <th>
            @Html.Label("Ürün Adı")
        </th> 

        <th>
            @Html.Label("Ürün İçerik")
        </th>

        <th>
            @Html.Label("Ürün Resmi")
        </th>
      
        <th>

            @Html.Label("Tarih")

        </th> 

        <th>

           @Html.Label("Kullanici Bilgileri")

        </th> 

        <th>

            @Html.ActionLink("Memleket", "Index", new { sortOrder = ViewBag.NameSortParm, currentFilter = ViewBag.CurrentFilter })

        </th>
         
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.kategoriler.kategoriAdi)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.urunAdi)
        </td> 

        <td>
            @Html.DisplayFor(modelItem => item.urunİcerik)
        </td>

        <td>
            <img width="75" src="@item.resim" />
        </td>
       

        <td>
            @Html.DisplayFor(modelItem => item.tarih)
        </td> 


        <td>
            @Html.DisplayFor(modelItem => item.kullanicilar.adsoyad) 
        </td> 

        <td>
            @Html.DisplayFor(modelItem => item.memleket.memleketAdi)
        </td>


        <td>
            @Html.ActionLink("Düzenle", "Edit", new { id=item.urunID }) |
            @Html.ActionLink("Sil", "Delete", new { id = item.urunID })
            
        </td>
    </tr>
}
      



</table>

<br />
Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount

@Html.PagedListPager(Model, page => Url.Action("Index", 
    new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }))